// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PortoSeguraAPI.Data;

#nullable disable

namespace PortoSeguraAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Documento", b =>
                {
                    b.Property<string>("NomeArquivo")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StatusUpload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("NomeArquivo");

                    b.HasIndex("UserId");

                    b.ToTable("Documentos", (string)null);
                });

            modelBuilder.Entity("Madrinha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ComprovanteResidenciaUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentoIdentidadeUrl")
                        .HasColumnType("text");

                    b.Property<string>("Motivacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecoDiaria")
                        .HasColumnType("numeric");

                    b.Property<bool>("TrilhaCursoCompleto")
                        .HasColumnType("boolean");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("integer");

                    b.Property<bool>("VerificadoIdentidade")
                        .HasColumnType("boolean");

                    b.Property<bool>("VerificadoResidencia")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioID")
                        .IsUnique();

                    b.ToTable("Madrinhas", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Usuaria",
                            NormalizedName = "USUARIA"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Madrinha",
                            NormalizedName = "MADRINHA"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Operador",
                            NormalizedName = "OPERADOR"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UsuarioRoles", (string)null);
                });

            modelBuilder.Entity("PortoSeguraAPI.Models.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAvaliacaoMadrinha")
                        .HasColumnType("boolean");

                    b.Property<int>("MadrinhaId")
                        .HasColumnType("integer");

                    b.Property<int>("Nota")
                        .HasColumnType("integer");

                    b.Property<int>("SolicitacaoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuariaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MadrinhaId");

                    b.HasIndex("SolicitacaoId");

                    b.HasIndex("UsuariaId");

                    b.ToTable("Avaliacoes", (string)null);
                });

            modelBuilder.Entity("PortoSeguraAPI.Models.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MadrinhaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MadrinhaId");

                    b.ToTable("Servicos", (string)null);
                });

            modelBuilder.Entity("PortoSeguraAPI.Models.Usuaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FotoPerfilUrl")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("VideoVerificacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("urlFacebook")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("urlInstagram")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("urlLinkedin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Solicitacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MadrinhaId")
                        .HasColumnType("integer");

                    b.Property<int>("QtdDiarias")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuariaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("MadrinhaId");

                    b.HasIndex("UsuariaId");

                    b.ToTable("Solicitacoes", (string)null);
                });

            modelBuilder.Entity("Documento", b =>
                {
                    b.HasOne("PortoSeguraAPI.Models.Usuaria", null)
                        .WithMany("Documentos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Madrinha", b =>
                {
                    b.HasOne("PortoSeguraAPI.Models.Usuaria", "Usuario")
                        .WithOne()
                        .HasForeignKey("Madrinha", "UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortoSeguraAPI.Models.Usuaria", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortoSeguraAPI.Models.Avaliacao", b =>
                {
                    b.HasOne("Madrinha", "Madrinha")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("MadrinhaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Solicitacao", "Solicitacao")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("SolicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortoSeguraAPI.Models.Usuaria", "Usuaria")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("UsuariaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Madrinha");

                    b.Navigation("Solicitacao");

                    b.Navigation("Usuaria");
                });

            modelBuilder.Entity("PortoSeguraAPI.Models.Servico", b =>
                {
                    b.HasOne("Madrinha", null)
                        .WithMany("Servicos")
                        .HasForeignKey("MadrinhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Solicitacao", b =>
                {
                    b.HasOne("Madrinha", "Madrinha")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("MadrinhaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortoSeguraAPI.Models.Usuaria", "Usuaria")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("UsuariaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Madrinha");

                    b.Navigation("Usuaria");
                });

            modelBuilder.Entity("Madrinha", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Servicos");

                    b.Navigation("Solicitacoes");
                });

            modelBuilder.Entity("PortoSeguraAPI.Models.Usuaria", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Documentos");

                    b.Navigation("Solicitacoes");
                });

            modelBuilder.Entity("Solicitacao", b =>
                {
                    b.Navigation("Avaliacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
